server:
    port: 80
    address: 127.0.0.1
    context-path: /
winter:
    application:
        name: My Demo Application
        id: MyApp
        version: 1.0.0-DEV
    namespaces:
        cacheTime: 10
    route:
        cacheTime: 10
myApp:
    value1: This is string
    value2: 99
    value3: true
    value4: 10.89

datasource:
    -   name: default
        url: "pdbc:sqlite:/opt/databases/mydb.sq3"
        username:
        password:
        validationQuery: SELECT 'Databse Connected'
        driverClass: dev\\winterframework\\pdbc\\pdo\\PdoDataSource
        connection:
            persistent: true
            errorMode: ERRMODE_EXCEPTION
            columnsCase: CASE_NATURAL
            connectionTimeoutSecs: 30
            autoCommit: true
            defaultrowprefetch: 100
